development:
  adapter: sqlite3
  database: database.db

test:
  adapter: sqlite3
  database: database.db

production:
adapter: postgresql
  host: localhost
  url: <%= ENV["HEROKU_POSTGRESQL_COBALT_URL"] %>